"""
Chronos foundation-model forecasting.

This module provides a zero-shot univariate Chronos forecast for the
hourly appliance-energy series.
"""

import numpy as np
import pandas as pd
import torch


MODEL_ID = "amazon/chronos-t5-small"


def get_device():
    """Return the best available inference device."""

    if torch.backends.mps.is_available():
        return "mps"

    if torch.cuda.is_available():
        return "cuda"

    return "cpu"


def load_chronos_model(model_id=MODEL_ID):
    """
    Load the pretrained Chronos model.

    The model is used zero-shot. No training or fine-tuning is performed
    on the appliance dataset.
    """

    from chronos import ChronosPipeline

    device = get_device()

    if device == "cuda":
        dtype = torch.bfloat16
    else:
        dtype = torch.float32

    print(f"Loading Chronos model: {model_id}")
    print(f"Device: {device}")
    print(f"Dtype: {dtype}")

    pipeline = ChronosPipeline.from_pretrained(
        model_id,
        device_map=device,
        torch_dtype=dtype,
    )

    return pipeline, device


def forecast_chronos(
    pipeline,
    y_train,
    horizon=24,
    num_samples=20,
):
    """
    Generate a probabilistic zero-shot Chronos forecast.

    Parameters
    ----------
    pipeline:
        Loaded ChronosPipeline.

    y_train:
        Historical appliance-energy observations.

    horizon:
        Forecast horizon in hours.

    num_samples:
        Number of forecast samples generated by Chronos.

    Returns
    -------
    forecast:
        Median forecast.

    lower:
        Lower 80% prediction bound.

    upper:
        Upper 80% prediction bound.
    """

    if isinstance(y_train, pd.Series):
        values = y_train.astype(float).dropna().values
    else:
        values = np.asarray(y_train, dtype=float)

    if values.ndim != 1:
        raise ValueError(
            "y_train must be a one-dimensional time series."
        )

    if len(values) < 100:
        raise ValueError(
            "Chronos requires a sufficiently long historical context."
        )

    context = torch.tensor(
        values,
        dtype=torch.float32,
    )

    print(
        f"Generating {horizon}-hour forecast "
        f"from {len(values)} historical observations..."
    )

    forecast_samples = pipeline.predict(
        context,
        prediction_length=horizon,
        num_samples=num_samples,
        temperature=1.0,
        top_k=50,
        top_p=1.0,
    )

    # Original Chronos output:
    # [number_of_series, number_of_samples, prediction_length]
    samples = forecast_samples[0]

    if hasattr(samples, "detach"):
        samples = samples.detach().cpu().numpy()

    samples = np.asarray(samples)

    if samples.ndim != 2:
        raise ValueError(
            f"Unexpected Chronos output shape: {samples.shape}"
        )

    # Probabilistic forecast summaries.
    lower = np.quantile(
        samples,
        0.10,
        axis=0,
    )

    median = np.quantile(
        samples,
        0.50,
        axis=0,
    )

    upper = np.quantile(
        samples,
        0.90,
        axis=0,
    )

    index = pd.date_range(
        start=y_train.index[-1] + pd.Timedelta(hours=1),
        periods=horizon,
        freq="h",
    )

    forecast = pd.Series(
        median,
        index=index,
        name="forecast",
    )

    lower = pd.Series(
        lower,
        index=index,
        name="lower_80",
    )

    upper = pd.Series(
        upper,
        index=index,
        name="upper_80",
    )

    return forecast, lower, upper